import { StyleSheet, Dimensions } from 'react-native'
const { width, height } = Dimensions.get('screen')

const styles = StyleSheet.create({
    popView: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.6)',
    },
    messageContainer: {
        flex: 1,
        width: width * .92,
        // minHeight: height * .1,
        paddingVertical: 10,
        backgroundColor: '#F58620',
        borderRadius: 20,
        alignSelf: 'center',
        marginVertical: height * .1,
    },
    confirmTitle: {
        fontFamily: 'Cairo-Bold',
        fontSize: 25,
        color: '#ffffff',
        textAlign: 'center',
        marginVertical: 10,
    },
    providerName: {
        fontFamily: 'Cairo-Bold',
        fontSize: 16,
        color: '#ffffff',
        marginHorizontal: 5,
    },
    closeButton: {
        position: 'absolute',
        width: 50,
        height: 50,
        backgroundColor: '#ffffff',
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        top: -10,
        left: -10,
    },
    closeIcon: {
        fontSize: 30,
        color: '#F58620',
        alignSelf: 'center',
    },
    headerView: {
        flexDirection: 'row-reverse',
        backgroundColor: '#ffffff',
        height: 50,
        alignItems: 'center',
    },
    rowView: {
        flexDirection: 'row-reverse',
        height: 50,
        alignItems: 'center',
    },
    productName: {
        flex: 2,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#F7921F',
        textAlign: 'center',
    },
    productCost: {
        flex: 1,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#F7921F',
        textAlign: 'center',
    },
    productCount: {
        flex: 1,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#F7921F',
        textAlign: 'center',
    },
    productTotalCost: {
        flex: 2,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#F7921F',
        textAlign: 'center',
    },
    rowName: {
        flex: 2,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#ffffff',
        textAlign: 'center',
    },
    rowCost: {
        flex: 1,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#ffffff',
        textAlign: 'center',
    },
    rowCount: {
        flex: 1,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#ffffff',
        textAlign: 'center',
    },
    rowTotalCost: {
        flex: 2,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#ffffff',
        textAlign: 'center',
    },
    infoRow: {
        flexDirection: 'row-reverse',
        height: 30,
        alignItems: 'center',
        marginHorizontal: 20,
    },
    infoTitle: {
        flex: 2,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#64615E',
        textAlign: 'right',
    },
    infoCost: {
        flex: 2,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#64615E',
        textAlign: 'center',
    },
    infoTag: {
        flex: 2,
        fontFamily: 'Cairo-Regular',
        fontSize: 15,
        color: '#64615E',
        textAlign: 'center',
    },
    infoList: {
        width: width * .91,
        height: 150,
        justifyContent: 'center',
        backgroundColor: 'rgba(246, 244, 241, .63)',
        borderRadius: 20,
        alignSelf: 'center',
        marginVertical: 5,
    },
    infoTotalTitle: {
        flex: 2,
        fontFamily: 'Cairo-Bold',
        fontSize: 17,
        color: '#64615E',
        textAlign: 'right',
    },
    infoTotalCost: {
        flex: 2,
        fontFamily: 'Cairo-Bold',
        fontSize: 17,
        color: '#64615E',
        textAlign: 'center',
    },
    infoTotalTag: {
        flex: 2,
        fontFamily: 'Cairo-Bold',
        fontSize: 17,
        color: '#64615E',
        textAlign: 'center',
    },
    sendButton: {
        alignSelf: 'center',
        backgroundColor: 'rgba(246,244,241,0.3)',
        borderRadius: 20,
        paddingHorizontal: 10,
        marginVertical: 5,
    },
    sendText: {
        fontFamily: 'Cairo-Regular',
        fontSize: 16,
        color: '#ffffff'
    }
})

export default styles